version: '3'

services:
  ghost:
    build: .
    ports:
      - "2368:2368"
    environment:
      # Ghost environment variables
      - url=http://localhost:2368
      - NODE_ENV=development
      # Database environment variables
      - database__client=postgres
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghost
      - database__connection__database=ghost
      - DATABASE_HOST=db
      - DATABASE_USER=ghost
      - DATABASE_PASSWORD=ghost
      - DATABASE_NAME=ghost
    depends_on:
      - db
    volumes:
      - ghost_content:/var/lib/ghost/content

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ghost
      - POSTGRES_PASSWORD=ghost
      - POSTGRES_DB=ghost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  ghost_content:
  postgres_data:
