services:
  - type: web
    name: jekyll
    runtime: static
    buildCommand: bundle install && bundle exec jekyll build
    publishDir: _site
    envVars:
      - key: JEKYLL_ENV
        value: production
