services:
  - type: web
    name: ghost-blog
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /ghost/api/admin/site/
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://your-ghost-blog.onrender.com
      - key: NODE_ENV
        value: production
      # Ghost-specific database connection variables
      - key: database__client
        value: postgres
      - key: database__connection__host
        fromDatabase:
          name: ghost-db
          property: host
      - key: database__connection__database
        fromDatabase:
          name: ghost-db
          property: database
      - key: database__connection__user
        fromDatabase:
          name: ghost-db
          property: user
      - key: database__connection__password
        fromDatabase:
          name: ghost-db
          property: password
      - key: database__connection__port
        value: "5432"
      - key: database__connection__ssl__rejectUnauthorized
        value: "false"
      # Ghost-specific mail variables
      - key: mail__transport
        value: SMTP
      - key: mail__options__service
        value: Mailgun
      - key: mail__options__host
        value: smtp.mailgun.org
      - key: mail__options__port
        value: "587"
      - key: mail__options__auth__user
        sync: false
      - key: mail__options__auth__pass
        sync: false

databases:
  - name: ghost-db
    plan: free
    databaseName: ghost
    ipAllowList: [] # only allow internal connections
