services:
  - type: web
    name: ghost-blog
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    port: 2368
    healthCheckPath: /
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    envVars:
      - key: url
        value: https://your-blog-url.onrender.com
      - key: database__client
        value: postgres
      - key: database__connection__host
        fromDatabase:
          name: ghost-db
          property: host
      - key: database__connection__database
        fromDatabase:
          name: ghost-db
          property: database
      - key: database__connection__user
        fromDatabase:
          name: ghost-db
          property: user
      - key: database__connection__password
        fromDatabase:
          name: ghost-db
          property: password
      - key: database__connection__ssl__rejectUnauthorized
        value: "false"

databases:
  - name: ghost-db
    plan: free
    databaseName: ghost
